### ISSUE TITLE
BWL Broodlord gate

### ISSUE THREAD

**Issue by Kamie1** [ChaosPA/PA-Bugtracker#11]
Killed Broodlord (yay us) but the gate to pass suppression room is bugged, looks like a visual bug. You can pass it if you jump to the left of the gate / wall. But we don't want to do that.

**Comment by ChaosPA** [comment]
I don't understand what the actual issue is with this description can you elaborate?

**Comment by Elthehablo666** [comment]
This was also an "issue" on retail I believe. Some classes can go past it, but it's not a problem

**Comment by ChaosPA** [comment]
Not a bug.
