### ISSUE TITLE
NE warrior Defense stance quest

### ISSUE THREAD

**Issue by Silvar1** [ChaosPA/PA-Bugtracker#12]
My NE warrior (Ashranna) cant get the 2nd part of the defence stance quest. 

I got the 1st part from Kyla windblade in dolonaar, went to darnassus and turned it in but thats as far as it goes.

I cant get (https://classicdb.ch/?quest=1683) - "Vorlus Vilehoof" its not offered as a quest.

https://classicdb.ch/?quest=1684  -- Completed

https://classicdb.ch/?quest=1683  -- Cannot accept, nothing shows up after I handed in the previous one.

**Comment by ChaosPA** [comment]
Plenty of warriors have finished this quest without any issues.

I also can't replicate the issue I'm sorry. Feel free to make a ticket to gain defensive stance from a GM.
