### ISSUE TITLE
WSG flag cap rep

### ISSUE THREAD

**Issue by perexx** [ChaosPA/PA-Bugtracker#2]
Capping a flag in WSG doesn’t give 2x rep like the server suggests it does. This was reported on discord and via in game ticket system several times

**Comment by ChaosPA** [comment]
The report doesn't involve the required information to resolve the issue.
May i re-direct you to: https://github.com/ChaosPA/PA-Bugtracker/issues/1

**Comment by perexx** [comment]
what more information is there to give? im not going to make a vid or take a screenshot or provide sources for something like this. its common sense, your server says rep gain is 2x. when you cap a flag you only get 1x rep. simple as that and a simple fix. the fact that you cant be bothered to take the time to test something like this is just baffling
