### ISSUE TITLE
AV rep from quests

### ISSUE THREAD

**Issue by perexx** [ChaosPA/PA-Bugtracker#3]
None of the one time AV quests are giving any rep. (Towers and bunkers, capture a graveyard, etc.)

**Comment by ChaosPA** [comment]
The report doesn't involve the required information to resolve the issue.
May i re-direct you to: https://github.com/ChaosPA/PA-Bugtracker/issues/1

**Comment by perexx** [comment]
how do you expect me to do this since i have all ready completed the quests and received no rep for them.  i don't have your GM access to the server to test these things. you can easily test these quests and fix them. AB was just released too and none of those quests are working either. you need to test content before releasing it and make sure it works properly. you cant just activate something in a file and call it a day.
