### ISSUE TITLE
Honor standing updated incorrectly.

### ISSUE THREAD

**Issue by torilon** [ChaosPA/PA-Bugtracker#4]
Bewssh told me he was going to sit out on tuesday in order for me to get standing 2 on the honor brackets. He only needed standing 3 to get Grand Marshal so it did not matter for him. We confirmed I was standing 2 an hour before the reset and reconfirmed it approximately 2-3 minutes before the reset. However, after the reset it showed I was standing 3 last week and I got rank 10.8, which most likely would be rank 11 if it wasn't for the standing not working correctly.

**Comment by ChaosPA** [comment]
We've done more research and can confirm the honor calculations are correct but too few players participate in PVP for the proper calculation to happen.
