### ISSUE TITLE
Majordomo chest can drop unique items in stacks of 2

### ISSUE THREAD

**Issue by elliepriest** [ChaosPA/PA-Bugtracker#5]
... leading to people not being able to loot it.

Tried:
- normal loot (error message: "You can't carry any more of those items.")
- shift-click to split the stack: doesn't work

**Comment by elliepriest** [comment]
Simplest fix: hard-code 1 eye and 1 leaf per chest. This will lead to the same drop rates as a randomized implementation in expectation (on a x2 loot server).

**Comment by ChaosPA** [comment]
Resolved.
