### ISSUE TITLE
Grel'borg the Miser doesnt drop q item.

### ISSUE THREAD

**Issue by Moresuperpro** [ChaosPA/PA-Bugtracker#6]
Im on the quest:  The Star, the Hand and the Heart (http://classicdb.ch/?quest=735).
And killed the ogre Grel'borg the Miser (http://classicdb.ch/?npc=2417#drop) but no Star of Xil'yeh (http://classicdb.ch/?item=4646) dropped.

**Comment by ChaosPA** [comment]
I can't replicate this issues, also the database contains shows the creature contains this as an drop.
