### ISSUE TITLE
Onyxia loot bugged on Horde side only?

### ISSUE THREAD

**Issue by taxoro** [ChaosPA/PA-Bugtracker#7]
2/2 of our onyxia kills has had bugged loot.

Blizzlike loot:

1 Onyxia head
1 Bag
2 Tier items
2-3(possible only 3) of the epic items
Trash

Our loot:
2 tier items
3 epic items.

Intended loot:
2 Onyxia head
2 Bag
4 Tier items
4-6(possible only 6) of the epic items

Picture of loot: https://i.imgur.com/fbMLl6s.jpg

**Comment by ChaosPA** [comment]
Looked into the issue couldn't yet find the solution during this maintenance. Will move it to next week. If you run into a loot issue make a ticket to get it resolved.

**Comment by ChaosPA** [comment]
Apparently, both Alliance and Horde had loot issues with Onyxia.

This was not because we didn't add the items to the loot table but the client limits the amount of loot possible per creature/boss.

We've removed green/rare drops from the boss in order for all tier items etc to be dropped.
